controller_list:
  - name: fake_arm_group_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_inter_group_controller
    type: $(arg execution_type)
    joints:
      - main_inter_joint
initial:  # Define initial robot poses.
  - group: inter_group
    pose: home