controller_list:
  - name: fake_arm_group_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home_pose