controller_list:
  - name: fake_arm_group_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_inter_group_controller
    type: $(arg execution_type)
    joints:
      - inter_joint_1
      - inter_joint_2
initial:  # Define initial robot poses.
  - group: arm_group
    pose: close_pose
  - group: inter_group
    pose: inter_pose